//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorTemplate.Server.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationResourceJapanese {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResourceJapanese() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorTemplate.Server.Properties.ValidationResourceJapanese", typeof(ValidationResourceJapanese).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CompareAttribute {
            get {
                return ResourceManager.GetString("CompareAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreditCardAttribute {
            get {
                return ResourceManager.GetString("CreditCardAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CustomValidationAttribute {
            get {
                return ResourceManager.GetString("CustomValidationAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DataTypeAttribute {
            get {
                return ResourceManager.GetString("DataTypeAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EmailAddressAttribute {
            get {
                return ResourceManager.GetString("EmailAddressAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EnumDataTypeAttribute {
            get {
                return ResourceManager.GetString("EnumDataTypeAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileExtensionsAttribute {
            get {
                return ResourceManager.GetString("FileExtensionsAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}文字以下でなければなりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MaxLengthAttribute {
            get {
                return ResourceManager.GetString("MaxLengthAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}文字以上でなければなりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MinLengthAttribute {
            get {
                return ResourceManager.GetString("MinLengthAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   無効な電話番号です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PhoneAttribute {
            get {
                return ResourceManager.GetString("PhoneAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}文字以上{2}文字以下でなければなりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RangeAttribute {
            get {
                return ResourceManager.GetString("RangeAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RegularExpressionAttribute {
            get {
                return ResourceManager.GetString("RegularExpressionAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は必須です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RequiredAttribute {
            get {
                return ResourceManager.GetString("RequiredAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は無効です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StringLengthAttribute {
            get {
                return ResourceManager.GetString("StringLengthAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UrlAttribute {
            get {
                return ResourceManager.GetString("UrlAttribute", resourceCulture);
            }
        }
    }
}
